version: "3.8"

services:
  streamer_api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    container_name: streamer
    volumes:
     - ./src:/src
    ports:
     - 8666:80
    networks:
       StreamerNet:
          ipv4_address: 172.16.6.2

networks:
  StreamerNet: # 172.16.5.x
    driver: bridge
    ipam:
      config:
        -
          subnet: 172.16.6.0/24
          gateway: 172.16.6.1